### ISSUE TITLE
Where to put code?

### ISSUE THREAD

**Issue by hauke68** [jreinke/magento-amqp#1]
Hi :)

Just one question:
Where do I have to put the example PHP code into?

Thanks for answer.

**Comment by Nolwennig** [comment]
You can put the code anywhere you want in your modules or in your core override because the hook is made by `amqp` helpers (cf: https://github.com/jreinke/magento-amqp/blob/master/app/code/community/Bubble/AMQP/etc/config.xml#L9)

**Comment by uzafar-epc** [comment]
how to create exchange? i am new to magento i have used rabbitmq in Yii but just getting to know how this works there is no documentation available
